/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.progmultifuncion;

/**
 *
 * @author Gab
 */
public class Vista3 extends javax.swing.JFrame {

    /**
     * Creates new form Vista1
     */
    public Vista3() {
        control = new Control();
        initComponents();
        setResizable(false);
        setLocationRelativeTo(null);
    
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        field2 = new javax.swing.JTextField();
        field1 = new javax.swing.JTextField();
        selector2 = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        selector1 = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        ConvertButton = new javax.swing.JButton();
        TempButton = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        LConvertButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(204, 204, 204));
        jPanel1.setLayout(null);

        field2.setEditable(false);
        field2.setBackground(new java.awt.Color(51, 255, 255));
        field2.setFont(new java.awt.Font("Consolas", 0, 14)); // NOI18N
        field2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                field2ActionPerformed(evt);
            }
        });
        field2.setBounds(280,100,190,30);
        jPanel1.add(field2);

        field1.setFont(new java.awt.Font("Consolas", 0, 14)); // NOI18N
        field1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                field1ActionPerformed(evt);
            }
        });
        field1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                field1KeyTyped(evt);
            }
        });
        field1.setBounds(40,100,180,30);
        jPanel1.add(field1);

        selector2.setFont(new java.awt.Font("Consolas", 0, 14)); // NOI18N
        selector2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Gramos", "Kilogramos", "Libras", "Onzas" }));
        selector2.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                selector2PropertyChange(evt);
            }
        });
        selector2.setBounds(280,48,190,22);
        jPanel1.add(selector2);

        jLabel1.setText(" --->");
        jLabel1.setBounds(230,48,40,21);
        jPanel1.add(jLabel1);

        selector1.setFont(new java.awt.Font("Consolas", 0, 14)); // NOI18N
        selector1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Gramos", "Kilogramos", "Libras", "Onzas" }));
        selector1.setToolTipText("");
        selector1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                selector1ActionPerformed(evt);
            }
        });
        selector1.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                selector1PropertyChange(evt);
            }
        });
        selector1.setBounds(40,49,180,20);
        jPanel1.add(selector1);


        jLabel2.setFont(new java.awt.Font("Consolas", 3, 14)); // NOI18N
        jLabel2.setText("Cambiar tipo de unidades");
        jLabel2.setBounds(10,200,310,20);
        jPanel1.add(jLabel2);

        ConvertButton.setFont(new java.awt.Font("Consolas", 3, 14)); // NOI18N
        ConvertButton.setText("Convertir");
        ConvertButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ConvertButtonActionPerformed(evt);
            }
        });
        ConvertButton.setBounds(180,140,130,40);
        jPanel1.add(ConvertButton);

        TempButton.setFont(new java.awt.Font("Consolas", 0, 12)); // NOI18N
        TempButton.setText("Temperatura");
        TempButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TempButtonActionPerformed(evt);
            }
        });
        TempButton.setBounds(30,270,140,30);
        jPanel1.add(TempButton);

        jLabel3.setFont(new java.awt.Font("Consolas", 3, 24)); // NOI18N
        jLabel3.setText("Conversor de unidades");
        jLabel3.setBounds(120,20,-1,-1);
        jPanel1.add(jLabel3);

        LConvertButton.setFont(new java.awt.Font("Consolas", 0, 12)); // NOI18N
        LConvertButton.setText("Longitud");
        LConvertButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LConvertButtonActionPerformed(evt);
            }
        });
        LConvertButton.setBounds(30,230,140,30);
        jPanel1.add(LConvertButton);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 504, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 323, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void selector2PropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_selector2PropertyChange
        // TODO add your handling code here:
    }//GEN-LAST:event_selector2PropertyChange

    private void selector1PropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_selector1PropertyChange
        // TODO add your handling code here:
    }//GEN-LAST:event_selector1PropertyChange

    private void selector1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_selector1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_selector1ActionPerformed

    private void field1KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_field1KeyTyped
    
        control.numberValidator(evt, field1);
         
    }//GEN-LAST:event_field1KeyTyped

    private void field2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_field2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_field2ActionPerformed

    private void ConvertButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ConvertButtonActionPerformed
    
    control.weight_unitConverter(field1, field2, selector1, selector2);
        
    }//GEN-LAST:event_ConvertButtonActionPerformed

    private void TempButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TempButtonActionPerformed
     this.dispose();
     Vista2 Temp = new Vista2();
     Temp.setVisible(true);
    }//GEN-LAST:event_TempButtonActionPerformed

    private void LConvertButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LConvertButtonActionPerformed
     this.dispose();
     Vista1 Length = new Vista1();
     Length.setVisible(true);     
    }//GEN-LAST:event_LConvertButtonActionPerformed

    private void field1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_field1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_field1ActionPerformed

    private Control control;

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ConvertButton;
    private javax.swing.JButton LConvertButton;
    private javax.swing.JButton TempButton;
    private javax.swing.JTextField field1;
    private javax.swing.JTextField field2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JComboBox<String> selector1;
    private javax.swing.JComboBox<String> selector2;
    // End of variables declaration//GEN-END:variables
}
