/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.progmultifuncion;

import java.awt.Dimension;
import java.awt.Image;
import java.awt.Toolkit;
import javax.swing.ImageIcon;
import javax.swing.JButton;
import java.awt.Font;
import javax.swing.GroupLayout.Alignment;
import javax.swing.GroupLayout;
import java.awt.event.ActionListener;
import java.awt.event.ActionEvent;

/**
 *
 * @author Gab
 */
public class Vista1 extends javax.swing.JFrame {

    /**
     * Creates new form Vista1
     */
    public Vista1() {
        
        control = new Control();
        initComponents();
        setResizable(false);
        setLocationRelativeTo(null);

    }
   
    public Image getIconImage() {
   Image retValue = Toolkit.getDefaultToolkit().
         getImage(ClassLoader.getSystemResource("Image/icono.png"));


   return retValue;
}

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")

    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        field2 = new javax.swing.JTextField();
        field1 = new javax.swing.JTextField();
        selector2 = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        selector1 = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        ConvertButton = new javax.swing.JButton();
        TempButton = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        WeightButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setIconImage(getIconImage());

        jPanel1.setBackground(new java.awt.Color(204, 204, 204));
        jPanel1.setLayout(null);

        field2.setEditable(false);
        field2.setBackground(new java.awt.Color(51, 255, 255));
        field2.setFont(new java.awt.Font("Consolas", 0, 14)); // NOI18N
        field2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                field2ActionPerformed(evt);
            }
        });

        jPanel1.setLayout(null);

        field2.setBounds(276, 116, 190, 30);

        jPanel1.add(field2);
        
        field1.setFont(new java.awt.Font("Consolas", 0, 14)); // NOI18N
        field1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                field1KeyTyped(evt);
            }
        });
        
        field1.setBounds(36, 116, 180, 30);

        jPanel1.add(field1);
        
        selector2.setFont(new java.awt.Font("Consolas", 0, 14)); // NOI18N
        selector2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "milímetros", "centímetros", "decímetros", "metros", "Decámetros", "Hectómetros", "Kilómetros", "Pulgada", "Pie", "Yarda", "Milla" }));
        selector2.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                selector2PropertyChange(evt);
            }
        });

        Dimension preferredSize = selector2.getPreferredSize();

        selector2.setBounds(276, 86, 190, 23);

    
        jPanel1.add(selector2);
        jLabel1.setText(" --->");
        Dimension pSize = jLabel1.getPreferredSize();

 
       jLabel1.setBounds(230, 85, 36, 23);

        jPanel1.add(jLabel1);
        selector1.setFont(new java.awt.Font("Consolas", 0, 14)); // NOI18N
        selector1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "milímetros", "centímetros", "decímetros", "metros", "Decámetros", "Hectómetros", "Kilómetros", "Pulgada", "Pie", "Yarda", "Milla" }));
        selector1.setToolTipText("");
        selector1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                selector1ActionPerformed(evt);
            }
        });
        selector1.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                selector1PropertyChange(evt);
            }
        });
        

        Dimension p2Size = selector1.getPreferredSize();

  
        selector1.setBounds(33, 86, 180, 23);

        jPanel1.add(selector1);
        jLabel2.setFont(new java.awt.Font("Consolas", 3, 14)); // NOI18N
        jLabel2.setText("Cambiar tipo de unidades");
  
        jLabel2.setBounds(142, 215, 310, 20);

       jPanel1.add(jLabel2);
       
        ConvertButton.setFont(new java.awt.Font("Consolas", 3, 14)); // NOI18N
        ConvertButton.setText("Convertir");
        ConvertButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ConvertButtonActionPerformed(evt);
            }
        });
  
        ConvertButton.setBounds(176, 156, 130, 40);

        jPanel1.add(ConvertButton);
        TempButton.setFont(new java.awt.Font("Consolas", 0, 12)); // NOI18N
        TempButton.setText("Temperatura");
        TempButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TempButtonActionPerformed(evt);
            }
        });
  
        jPanel1.setLayout(null);

        TempButton.setBounds(26, 246, 140, 43);

        jPanel1.add(TempButton);
        jLabel3.setFont(new java.awt.Font("Consolas", 3, 24)); // NOI18N
        jLabel3.setText("Conversor de unidades");
 
        jPanel1.setLayout(null);

  
        Dimension p3Size = jLabel3.getPreferredSize();

        jLabel3.setBounds(113, 21, 329, 23);

         jPanel1.add(jLabel3);

        WeightButton.setFont(new java.awt.Font("Consolas", 0, 12)); // NOI18N
        WeightButton.setText("Masa");
        WeightButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                WeightButtonActionPerformed(evt);
            }
        });

        jPanel1.setLayout(null);


        WeightButton.setBounds(176, 247, 165, 42);

        jPanel1.add(WeightButton);
        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        layout.setHorizontalGroup(
        	layout.createParallelGroup(Alignment.LEADING)
        		.addComponent(jPanel1, GroupLayout.DEFAULT_SIZE, 514, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
        	layout.createParallelGroup(Alignment.LEADING)
        		.addComponent(jPanel1, GroupLayout.DEFAULT_SIZE, 323, Short.MAX_VALUE)
        );
        getContentPane().setLayout(layout);
        
        JButton btnLongitud = new JButton();
        btnLongitud.addActionListener(new ActionListener() {
        	public void actionPerformed(ActionEvent e) {
        		Control.changeDataUI(selector1, selector2, "longitud");
        	}
        });
        btnLongitud.setText("Longitud");
        btnLongitud.setFont(new Font("Consolas", Font.PLAIN, 12));
        btnLongitud.setBounds(351, 248, 140, 41);
        jPanel1.add(btnLongitud);

        pack();
    }

    private void selector2PropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_selector2PropertyChange
        // TODO add your handling code here:
    }//GEN-LAST:event_selector2PropertyChange

    private void selector1PropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_selector1PropertyChange
        // TODO add your handling code here:
    }//GEN-LAST:event_selector1PropertyChange

    private void selector1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_selector1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_selector1ActionPerformed

    private void field1KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_field1KeyTyped
    
        control.numberValidator(evt, field1);
         
    }

    private void field2ActionPerformed(java.awt.event.ActionEvent evt) {
        
    }

    private void ConvertButtonActionPerformed(java.awt.event.ActionEvent evt) {
    	
    switch(control.buttonControler){    
    case 1:
    	control.lUnitConverter(field1, field2, selector1, selector2);
    	break;
    	
    case 2:
    	control.tempUnitConverter(field1, field2, selector1, selector2);
    	break;
    
    case 3:
    	control.weightUnitConverter(field1, field2, selector1, selector2);
    	break;
    default:
    	break;
    }
    
        
    }

    private void TempButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TempButtonActionPerformed
    
    Control.changeDataUI(selector1, selector2, "temperatura");

    }

    private void WeightButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_WeightButtonActionPerformed
    	
     Control.changeDataUI(selector1, selector2, "masa");	
         	
    }

    private Control control;

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ConvertButton;
    private javax.swing.JButton TempButton;
    private javax.swing.JButton WeightButton;
    private javax.swing.JTextField field1;
    private javax.swing.JTextField field2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JComboBox<String> selector1;
    private javax.swing.JComboBox<String> selector2;
}
